### ISSUE TITLE
Volume slider

### ISSUE THREAD

**Issue by gerard33** [gerard33/sony-bravia#1]
Volume slider in Domoticz does not change volume on TV.
Issue is in bravia.py function which changes volume.

**Comment by markcame** [comment]
i'm able to set from localtest.py the volume level but from domoticz  the actual level i don't know how to pass, i've removed multiply by 100 seems to accept 0-100 value

**Comment by gerard33** [comment]
Can you show me what you have changed? Only removed the * 100 from the bravia.py function?
Because I have tried that but it didn't work on my TV.

**Comment by markcame** [comment]
yes i've removed *100 from bravia.py and to test i've put hardcoded in localtest.py i've put 

`test_vol = x.set_volume_level("13")`

and runnig the script the volume going up from the actual level to 13

**Comment by markcame** [comment]
from domoticz how can i pass the value ?

**Comment by markcame** [comment]
Fixed,

you have to change
`self.tvVolume = Level`
`_tv.set_volume_level(self.tvVolume)`

with 

`#self.tvVolume = Level (can be removed)`
`_tv.set_volume_level(str(Level))`

And remove *100 in bravia.py

**Comment by markcame** [comment]
Here I've found some documentation 
[http://aydbe.com/assets/uploads/2014/11/json.txt](http://aydbe.com/assets/uploads/2014/11/json.txt)

**Comment by gerard33** [comment]
Nice, thanks! I had removed the *100 when trying, but didn't sent the volume value as string.
Just changed it and it works now.
Will be available in the next release.

**Comment by gerard33** [comment]
Fixed in commit 7aa3dbb.
