### ISSUE TITLE
Use universal method for source names

### ISSUE THREAD

**Issue by gerard33** [gerard33/sony-bravia#5]
The source inputs are currently hardcoded (HDMI 1/MHL, HDMI 2, HDMI 3, HDMI 4).
The sources can be retrived from the TV with `get_source('extInput:hdmi')`.

Let's see if we can use that in the code.

Another solution is to use a text field in the Domoticz hardware page where you can set the sources.

**Comment by markcame** [comment]
hi  gerard33 on my tv the inputs are coded as follow
` Playing: HDMI 1
TV model: KDL-42W805A
Volume: 19
Source list: [{'title': 'HDMI 1', 'index': 0, 'uri': 'extInput:hdmi?port=1'}, {'title': 'HDMI 2/MHL', 'index': 1, 'uri': 'extInput:hdmi?port=2'}, {'title': 'HDMI 3', 'index': 2, 'uri': 'extInput:hdmi?port=3'}, {'title': 'HDMI 4', 'index': 3, 'uri': 'extInput:hdmi?port=4'}]
`

**Comment by gerard33** [comment]
Thanks! The /MHL part is on a different HDMI source on your TV.
Will change the code so it will not check the /MHL part, then it should already work.
HDMI3 and HDMI4 are already shown correctly on your selector switch isn't it?

**Comment by gerard33** [comment]
Fixed in commit 7aa3dbb.
