### ISSUE TITLE
Domoticz Beta

### ISSUE THREAD

**Issue by simonrb2000** [gerard33/sony-bravia#9]
Hi All,

Just got a Smart Bravia Android TV, looking to implement it with Domoticz using this plugin. I don't run the beta version of Domoticz. Is it worth updating to the beta? Have you guys had any issues with it?

Many Thanks

**Comment by vgr28** [comment]
Was working very well on beta before the Python stuff and changes. Now it's still crashing on my side.

**Comment by simonrb2000** [comment]
I might leave it for a while then.

Thanks for the info.

On 11 Jul 2017, at 18:34, vgr28 <notifications@github.com<mailto:notifications@github.com>> wrote:


Was working very well on beta before the Python stuff and changes. Now it's still crashing on my side.

**Comment by gerard33** [comment]
@simonrb2000 I guess it depends on the system being used. I have this plugin running for many days now without one issue on my Ubuntu Server with Domoticz v3.8025.
But on the forum I still see issues with the Python plugins on Raspberry Pi. Hopefully that will be fixed in the Python framework soon.

**Comment by simonrb2000** [comment]
Now this is the stable version, I have tried to use your plugin and getting the following issue in the log

2017-08-06 18:16:15.619 Error: () failed to load 'plugin.py', Python Path used was ':/usr/lib/python3.4/:/usr/lib/python3.4/plat-arm-linux-gnueabihf:/usr/lib/python3.4/lib-dynload'.
2017-08-06 18:16:15.619 Error: (Living Room TV) Module Import failed, exception: 'ImportError'
2017-08-06 18:16:15.619 Error: (Living Room TV) Module Import failed: ' Name: plugin'

I installed python 3.4

**Comment by gerard33** [comment]
@simonrb2000, can you try the 1.2 version from https://github.com/gerard33/sony-bravia/tree/development?
Make sure to take plugin.py and bravia.py from that branch.

**Comment by simonrb2000** [comment]
I assume I am using 1.2? I just updated it using
cd domoticz/plugins/sony-bravia
git pull

**Comment by gerard33** [comment]
Nope, version 1.2 is on the development branch. The master branch has version 1.1 which gives that error.

**Comment by simonrb2000** [comment]
Ah, All loaded now! Thank you. Although I have entered my TV's Mac and IP address with little success.

I will go have to tinker and see if I can get it working 👍 

Log says 
2017-08-06 22:27:02.442 Error: (Living Room TV) HTTPError: HTTP Error 403: Forbidden

**Comment by gerard33** [comment]
Allright, then I will push v1.2 to master.
Can you share some more information on what's happening / missing?

**Comment by simonrb2000** [comment]
My TV is an Android TV, just reading through the forum thread.. something about cookies or something lol

**Comment by gerard33** [comment]
I think an Android should work without cookies. Have you set the PSK in the TV following this instruction https://github.com/gerard33/sony-bravia#sony-bravia-plugin-instructions?

**Comment by simonrb2000** [comment]
Haha.. Erm... 😳

Working great now.. I think I'll change the volume behaviour. Rather than mute, Turn the TV on and off. That way I should be able to export to Homebridge and control volume and turn on and off using 1 switch 👍

**Comment by gerard33** [comment]
Great it's working now :+1:  Was it the PSK setting?

You mean you'll change that in the Python code?
And the volume is only working if you are using the TV speakers. If you have an amplifier connected to the TV the volume slider isn't working.

**Comment by simonrb2000** [comment]
I'll change it in the python code if I am brave enough lol

Yes it was the PSK setting. Although Domoticz just crashed. I'll keep an eye on logs. Is there any logs I can send over that might help with the crashing?

**Comment by gerard33** [comment]
Just the Domoticz log would help. If there is no log available, you can start Domoticz (./domoticz) from the command line, that will give some more info.

Make sure there is no file script_device_PIRsmarter.py is the scripts/python directory. I just updated here to the stable version and that file made Domoticz crash over here.

**Comment by simonrb2000** [comment]
I do have that file! What is it used for? Should I just delete it? Domoticz has only crashed once in the last 10 hours and that was after I got this plugin working. Hoping just a coincidence. 

Just googling to see if there is a way to get Kodi and/or Amazon apps to load like Netflix so I can add them into the selector. Hmmm

**Comment by gerard33** [comment]
It's a demo file which got there on accident I think, since it's causing Domoticz to crash.
See http://www.domoticz.com/forum/viewtopic.php?t=17778&start=40#p137809 and https://www.domoticz.com/forum/viewtopic.php?t=17866#p137525.

Just delete the file, it's an very old example which doesn't work anymore.

Regarding the Kodi/Amazon app, I don't think that will work. The Netflix app is started up using a special code. I haven't seen that code for other apps.
https://github.com/gerard33/sony-bravia/blob/master/plugin.py#L217

**Comment by simonrb2000** [comment]
Ah, got ya. Thank you for taking the time to reply to me on a Sunday evening! 

I'll delete the file now! Guessed as much with the Kodi/Amazon thing. 

One last thing, I see the volume doesn't get updated from the TV. For example if I change the TV volume using the remote it isn't reflected within domoticz. Not sure if that has been mentioned before?

**Comment by gerard33** [comment]
When using the TV speakers, the volume in Domoticz should change.
But if you have an amp attached that will not work.

**Comment by simonrb2000** [comment]
No speakers attached. Its not updating at the mo. I'll keep an eye on it

**Comment by gerard33** [comment]
And you can control the volume of the TV with the Domoticz slider? And mute/unmute from Domoticz?

**Comment by simonrb2000** [comment]
Correct, it's just the other way doesn't work.

On 7 Aug 2017, at 21:52, gerard33 <notifications@github.com<mailto:notifications@github.com>> wrote:


And you can control the volume of the TV with the Domoticz slider? And mute/unmute from Domoticz?

**Comment by gerard33** [comment]
Have you set Volume bar to True in the Domoticz Hardware page? If this is set to false it will not update the volume bar with data from the TV.

**Comment by simonrb2000** [comment]
I can confirm this was and still is set to true

On 7 Aug 2017, at 22:02, gerard33 <notifications@github.com<mailto:notifications@github.com>> wrote:


Have you set Volume bar to True in the Domoticz Hardware page? If this is set to false it will not update the volume bar with data from the TV.

**Comment by gerard33** [comment]
Can you setup localtest.py and run it? It will show the volume of your TV. Is that value correct?

And then re-run it after you have changed the volume on your TV (with the TV remote).
Is it then showing the correct value?

**Comment by simonrb2000** [comment]
I could do Gerard however I think I have found the issue. It appears to be when using the apps on the Android side of the TV. There is no feedback, as soon as I start watching TV on one of the HDMI channels the feedback works. Strange thing is the controls work when in the apps, just not feedback

**Comment by gerard33** [comment]
Then I don't think there is anything I can do about that.
Can't test it at least since I don't have an Android model ;-)

**Comment by simonrb2000** [comment]
Ah, shame. Well if I can test anything or provide logs then let me know. Thanks for your help! 

I'll close this as its working and not crashing Domoticz at all 👍
